#!/bin/sh

for i in * ; do
  if test -d $i ; then
    cd $i || exit 1
    if test -x ./configure; then
      ./configure $COMPILE_ARGS || exit 1
      make || exit 1
    else
      for j in * ; do
        cd $j || exit 1
        ./configure $COMPILE_ARGS || exit 1
        make || exit 1
        cd ..
      done
    fi
    cd ..
  fi
done
