#!/bin/bash

if test "x$AUTOMAKE_DIR" = "x"; then
  if test -d /usr/local/share/automake; then
    AUTOMAKE_DIR=/usr/local/share/automake
  fi
  if test -d /usr/share/automake; then
    AUTOMAKE_DIR="/usr/share/automake"
  fi
fi

for f in install-sh mkinstalldirs missing; do
  cp -av $AUTOMAKE_DIR/$f .
done

aclocal $ACLOCAL_FLAGS
automake --foreign --add-missing --copy
touch depcomp
autoconf
export CFLAGS='-O2 -Wall -pipe -g'
echo "CFLAGS=$CFLAGS"
echo "./configure $@"
./configure $@
unset CFLAGS
make
