#!/bin/sh

aclocal $ACLOCAL_FLAGS || exit 1
autoheader || exit 1
automake --add-missing --copy --foreign || exit 1
touch depcomp || exit 1
autoconf || exit 1
./configure $* || exit 1
if [ -z "$GITCOMPILE_NO_MAKE" ]; then
  make || exit 1
fi
